x-superset-image: &superset-image apache/superset:2.0.1
x-superset-depends-on: &superset-depends-on
  - redis

x-superset-volumes: &superset-volumes
  - ./docker:/app/docker
  - ./volumes/superset_home_nista:/app/superset_home

x-superset-networks: &superset-networks
  - nista_net 

version: "3.7"
services:

  redis:
    image: redis:7
    container_name: nista_superset_cache
    restart: unless-stopped
    volumes:
      - redis:/data
    networks: *superset-networks

  superset:
    env_file: docker/.env
    image: *superset-image
    container_name: nista_superset_app
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    user: "root"
    restart: unless-stopped
    ports:
      - 8088:8088
    depends_on: *superset-depends-on
    volumes: *superset-volumes
    networks: *superset-networks

  superset-init:
    image: *superset-image
    container_name: nista_superset_init
    command: ["/app/docker/docker-init.sh"]
    env_file: docker/.env
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      disable: true
    networks: *superset-networks

  superset-worker:
    image: *superset-image
    container_name: nista_superset_worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    env_file: docker/.env
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      test: ["CMD-SHELL", "celery inspect ping -A superset.tasks.celery_app:app -d celery@$$HOSTNAME"]
    networks: *superset-networks

  superset-worker-beat:
    image: *superset-image
    container_name: nista_superset_worker_beat
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    env_file: docker/.env
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      disable: true
    networks: *superset-networks

volumes:
  superset_home_nista:
    external: true
  db_home_nista:
    external: true
  redis:
    external: false

networks:
  nista_net:
    external: true




